### PR TITLE
Attempt to fix the Layout value displayed on the form.

### PR DESCRIPTION
**Pull request by ruchern**
An attempt to fix the error displaying the raw layout file as shown in the screenshot below.

This may not be a very clean fix after all.

screen shot 2017-01-20 at 4 25 24 am

Signed-off-by: Ru Chern <iruchern@gmail.com>

### CODE REVIEW

**Comment by austintoddj** [comment]
@ruchern Looking at the screenshot you provided, what error are you seeing?

**Comment by ruchern** [comment]
@austintoddj Is "canvas::frontend.blog.post" intended? Otherwise, I explicitly set "Default" as the value to the layout. While this pull request is still open, I am still going to find ways to fix this in a cleaner method.

**Comment by austintoddj** [comment]
@ruchern It's actually intentional to not allow the user to edit the layout. Editing the layout would need to be done in the code. The value is displayed simply for an FYI, not meant to be editable.

**Comment by ruchern** [comment]
@austintoddj I see, thanks. I thought the raw layout filename displayed was an error.

**Pull request closed without merging**
