### PR TITLE
add changyan comment box

### PR DESCRIPTION
**Pull request by Qsnh**
I'am from china.It's glad to use canvas.But I found that chinese users can not use disqus,so I added the changyan comment tool it is a well-known chinese comment tool like disqus.

### CODE REVIEW

**Comment by austintoddj** [comment]
Thanks for sending this @Qsnh! I'll take a look at this and merge it in as soon as I've verified it doesn't need any changes. 👍

**Comment by austintoddj** [comment]
@Qsnh Quick question on this PR. Do you think it'd be wise to choose one comment system over another, or have both readily available to the user? Would it be smart to just check for the environment timezone, and if it's in China, then we give the Changyan comments, and if not then we use Disqus?

**Comment by Qsnh** [comment]
@austintoddj yes,sure,i will change this pr.

**Comment by Qsnh** [comment]
#140

**Pull request closed without merging**
