### PR TITLE
Frontend localization

### PR DESCRIPTION
**Pull request by florinfratica**
This pull request contains my implementation for the following feature request: [Localization for Canvas Paper theme #317](https://github.com/cnvs/canvas/issues/317).

All the text from the frontend of the blog must be included in the `resources/lang/en/frontend.php` file and will be displayed in the blade views using the `trans()` helper function. Future PR must be checked so that they don't contain plain text inside views. More info about localization can be found in the official Laravel documentation: [https://laravel.com/docs/5.4/localization](https://laravel.com/docs/5.4/localization).

I also added a command for publishing translation files. This will copy the default translation files outside of the `vendor` folder in `resources/vendor/canvas`. You can use the `php artisan help canvas:publish:translation` command to see it's description and available options.

If anyone wants to translate the blog I suggest following the instructions below:

1. run `php artisan canvas:publish:translation`
2. set **locale** inside the `config/app.php` file to your language ISO code. This will also change Carbon localization (see [http://carbon.nesbot.com/docs/#api-localization](http://carbon.nesbot.com/docs/#api-localization)).
3. make a copy of the `en` folder inside `resources/vendor/canvas` and rename it to your language ISO code
4. edit the **frontend.php** file inside your newly created folder

### CODE REVIEW

**Comment by austintoddj** [comment]
Thanks for submitting this @florinfratica! Let me take a closer look at this in the next couple days and get back to you with any changes or breaking parts that I see.

**Comment by austintoddj** [comment]
@florinfratica Sorry I'm just now getting to this. I'm ready to merge it into the `develop` branch, but would you mind taking care of the two conflicting files first? As soon as that's good I'll merge it in 👍

**Comment by florinfratica** [comment]
@austintoddj I didn't manage to commit my changes to this PR. I've send you an email.

**Comment by reliq** [comment]
Addressed with https://github.com/cnvs/easel/commit/7a74243dc7d076bd222bf348627813e97453f122 
Thank you @florinfratica!

**Pull request closed without merging**
